* description
  This is a collection of common lisp functions intended to create
  latex code. This collection is work in progress. While I am not confident that 
anyone but myself can be productive using this library, I enjoy using it
and therefore decided to publish it. If nothing else, it might provide some 
ideas and inspiration to others.
This work can be intesting for you if
- you write a lot of complicated latex
- you use many semantic macros
- programming in latex feels not as nice as programming lisp
  
* motivation
Programming in latex can be cumbersome, so I decided to
  have my latex code written for me by lisp. This allows creating very
  powerful abstractions leading to concise and semantic source code.

* getting started
  clone this repository and read the examples in the example folder. 
  They intend to demonstrate how this library can be used and integrated into 
  your workflow.

* integration into workflow
There are at least three possible ways to use this:
** generate entire file using lisp
** generate small files using lisp and input them into your main document
** using emacs org-mode
  Personally, I use emacs org mode, which allows exporting to latex.
  Moreover, it allows evaluating source code and exporting the
  results. These functions allow a very nice integration of normal
  text with lisp-generated latex text.
